/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JDialog;
import javax.swing.JFrame;


/**
 *
 * @author ASUS
 */
public class petugas extends javax.swing.JFrame {
    private Connection connection;
    private DefaultTableModel tableModel;

    /**
     * Creates new form petugas
     */
    public petugas() {
        initComponents();
        initDatabase();
        initTableModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output_petugas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_petugas = new javax.swing.JTextField();
        no_hp = new javax.swing.JTextField();
        alamat_petugas = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        pindahTransaksi = new javax.swing.JButton();
        pindahBarang = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data Petugas");
        setBackground(new java.awt.Color(255, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        output_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "No Hp", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(output_petugas);

        jLabel1.setText("Nama Petugas");

        jLabel2.setText("No HP");

        jLabel3.setText("Alamat");

        nama_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_petugasActionPerformed(evt);
            }
        });

        tambah.setText("Tambah Data");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        Edit.setBackground(new java.awt.Color(255, 255, 51));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(255, 51, 51));
        hapus.setText("Hapus Data");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        pindahTransaksi.setText("transaksi");
        pindahTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pindahTransaksiActionPerformed(evt);
            }
        });

        pindahBarang.setText("Barang");
        pindahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pindahBarangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setText("DATA PETUGAS");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel5.setText("TOKO ABDI JAYA");

        jLabel6.setText("Pindah Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pindahTransaksi)
                        .addGap(18, 18, 18)
                        .addComponent(pindahBarang))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Edit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tambah)
                                    .addComponent(nama_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(no_hp)
                                    .addComponent(alamat_petugas))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nama_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alamat_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(hapus)
                    .addComponent(Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pindahTransaksi)
                    .addComponent(pindahBarang))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pindahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pindahBarangActionPerformed
        // TODO add your handling code here:
        JFrame  NewJFrame = new NewJFrame();
        this.dispose();

        JDialog dialog = new JDialog(this, "Data Buku", true);
        dialog.getContentPane().add(NewJFrame.getContentPane());
        dialog.setSize(NewJFrame.getSize());
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        // Menampilkan dialog
        dialog.setVisible(true);
    }//GEN-LAST:event_pindahBarangActionPerformed

    //Pindah Jframe
    private void pindahTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pindahTransaksiActionPerformed
        JFrame transaksi = new transaksi();
        this.dispose();

        JDialog dialog = new JDialog(this, "Transaksi", true);
        dialog.getContentPane().add(transaksi.getContentPane());
        dialog.setSize(transaksi.getSize());
        dialog.setLocationRelativeTo(this);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        // Menampilkan dialog
        dialog.setVisible(true);

    }//GEN-LAST:event_pindahTransaksiActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = output_petugas.getSelectedRow();
        if (selectedRow != -1) {
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                hapusDataPetugas(selectedRow); // Hapus dari database
                tableModel.removeRow(selectedRow); // Hapus dari tabel
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus terlebih dahulu", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        int selectedRow = output_petugas.getSelectedRow();
        if (selectedRow != -1) {
            String namaPetugas = tableModel.getValueAt(selectedRow, 0).toString();
            String no_hpPetugas = tableModel.getValueAt(selectedRow, 1).toString();
            String alamatPetugas = tableModel.getValueAt(selectedRow, 2).toString();

            // Tampilkan dialog atau form untuk mengedit data, dan simpan perubahannya dalam variabel namaBarangBaru dan hargaBarangBaru

            String namaPetugasBaru = JOptionPane.showInputDialog(this, "Masukkan Nama Petugas Baru", namaPetugas);
            String no_hpPetugasBaru = JOptionPane.showInputDialog(this, "Masukkan no hp Baru", no_hpPetugas);
            String alamatPetugasBaru = JOptionPane.showInputDialog(this, "Masukkan alamat Baru", alamatPetugas);

            // Perbarui data dalam tabel
            tableModel.setValueAt(namaPetugasBaru, selectedRow, 0);
            tableModel.setValueAt(no_hpPetugasBaru, selectedRow, 1);
            tableModel.setValueAt(alamatPetugasBaru, selectedRow, 2);

            // Perbarui data dalam database
            updateDataPetugas(namaPetugas, no_hpPetugas, alamatPetugas, namaPetugasBaru, no_hpPetugasBaru, alamatPetugasBaru);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit terlebih dahulu", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EditActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        String namaPetugas = nama_petugas.getText();
        String no_hpPetugas= no_hp.getText();
        String alamatPetugas = alamat_petugas.getText();

        if (!namaPetugas.isEmpty() && !no_hpPetugas.isEmpty()&& !alamatPetugas.isEmpty()) {

            // Tambahkan baris baru ke dalam model tabel
            Object[] row = {namaPetugas, no_hpPetugas, alamatPetugas};
            tableModel.addRow(row);

            // Kosongkan input setelah ditambahkan ke tabel
            nama_petugas.setText("");
            no_hp.setText("");
            alamat_petugas.setText("");

            // Simpan data ke database
            simpanDatabasePetugas(namaPetugas, no_hpPetugas, alamatPetugas);
        } else {
            JOptionPane.showMessageDialog(this, "Isi Nama , no hp dan alamat petugas terlebih dahulu", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void nama_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_petugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_petugasActionPerformed
    
      
        
    //Meelakukan Edit Pada Data
    private void updateDataPetugas(String namaPetugas, String no_hpPetugas, String alamatPetugas, String namaPetugasBaru, String no_hpPetugasBaru, String alamatPetugasBaru) {
        String query = "UPDATE petugas SET nama = ?, no_hp = ?, alamat = ? WHERE nama = ? AND no_hp = ? AND alamat = ?";

            try {
                PreparedStatement statement = connection.prepareStatement(query);
                statement.setString(1, namaPetugasBaru);
            statement.setString(2, no_hpPetugasBaru);
            statement.setString(3, alamatPetugasBaru);
            statement.setString(4, namaPetugas);
            statement.setString(5, no_hpPetugas);
            statement.setString(6, alamatPetugas);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    } 
    
    private void hapusDataPetugas(int rowIndex) {
        String namaPetugas = tableModel.getValueAt(rowIndex, 0).toString();
        String no_hpPetugas = tableModel.getValueAt(rowIndex,1).toString();
        String alamatPetugas = tableModel.getValueAt(rowIndex, 2).toString();

        String query = "DELETE FROM petugas WHERE nama = ? AND no_hp = ? AND alamat = ?" ;

        try {
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, namaPetugas);
            statement.setString(2, no_hpPetugas);
            statement.setString(3, alamatPetugas);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void simpanDatabasePetugas(String namaPetugas, String no_hpPetugas, String alamatPetugas){
        String query = "INSERT INTO petugas (nama, no_hp, alamat) VALUES (?, ?, ?)";

        try {
            PreparedStatement statement = connection.prepareStatement(query);
            statement.setString(1, namaPetugas);
            statement.setString(2, no_hpPetugas);
            statement.setString(3, alamatPetugas);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void initDatabase() {
        String url = "jdbc:mysql://localhost:3306/toko_abdi_jaya";
        String username = "root";
        String password = "";

        try {
            connection = DriverManager.getConnection(url, username, password);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void initTableModel(){
        String [] columnName = {"Nama","no_hp","alamat"};
        tableModel = new DefaultTableModel(columnName,0);
        output_petugas.setModel(tableModel);
        mengambilDatabase();
    }
    
    private void mengambilDatabase() {
        String query = "SELECT nama, no_hp,alamat FROM petugas";

        try {
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                String namaPetugas = resultSet.getString("nama");
                String no_hpPetugas = resultSet.getString("no_hp");
                String alamatPetugas = resultSet.getString("alamat");
                Object[] row = {namaPetugas, no_hpPetugas,alamatPetugas};
                tableModel.addRow(row);
            }

            resultSet.close();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField alamat_petugas;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_petugas;
    private javax.swing.JTextField no_hp;
    private javax.swing.JTable output_petugas;
    private javax.swing.JButton pindahBarang;
    private javax.swing.JButton pindahTransaksi;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
